version: "2"

linters:
  default: standard
  enable:
    - revive
    - errorlint
  settings:
    revive:
      rules:
        - name: exported
        - name: package-comments

formatters:
  enable:
    - gofmt
