// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package testdb

import (
	"context"
)

const countItemsByName = `-- name: CountItemsByName :one
SELECT count(*) FROM items WHERE name = $1
`

func (q *Queries) CountItemsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertItem = `-- name: InsertItem :one
INSERT INTO items (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) InsertItem(ctx context.Context, name string) (Item, error) {
	row := q.db.QueryRow(ctx, insertItem, name)
	var i Item
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const isolationLevel = `-- name: IsolationLevel :one
SELECT current_setting('transaction_isolation')::text
`

func (q *Queries) IsolationLevel(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, isolationLevel)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}
