// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyKey struct {
	Scope      string
	Key        string
	ResourceID string
}

type Outbox struct {
	ID        int64
	Topic     string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

type Payment struct {
	ID        string
	AccountID string
	Amount    int64
	Status    string
	Reference string
}
