// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :execrows
INSERT INTO idempotency_keys (scope, key, resource_id)
VALUES ($1, $2, $3)
ON CONFLICT (scope, key) DO NOTHING
`

type ClaimIdempotencyKeyParams struct {
	Scope      string
	Key        string
	ResourceID string
}

func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotencyKey, arg.Scope, arg.Key, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countIdempotencyKeys = `-- name: CountIdempotencyKeys :one
SELECT count(*) FROM idempotency_keys WHERE scope = $1 AND key = $2
`

type CountIdempotencyKeysParams struct {
	Scope string
	Key   string
}

func (q *Queries) CountIdempotencyKeys(ctx context.Context, arg CountIdempotencyKeysParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIdempotencyKeys, arg.Scope, arg.Key)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOutbox = `-- name: CountOutbox :one
SELECT count(*) FROM outbox
`

func (q *Queries) CountOutbox(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOutbox)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT resource_id FROM idempotency_keys WHERE scope = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	Scope string
	Key   string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Scope, arg.Key)
	var resource_id string
	err := row.Scan(&resource_id)
	return resource_id, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, account_id, amount, status, reference FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Status,
		&i.Reference,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (topic, payload) VALUES ($1, $2)
`

type InsertOutboxParams struct {
	Topic   string
	Payload []byte
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.Topic, arg.Payload)
	return err
}

const insertPayment = `-- name: InsertPayment :exec
INSERT INTO payments (id, account_id, amount, status) VALUES ($1, $2, $3, $4)
`

type InsertPaymentParams struct {
	ID        string
	AccountID string
	Amount    int64
	Status    string
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) error {
	_, err := q.db.Exec(ctx, insertPayment,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.Status,
	)
	return err
}

const updatePaymentResult = `-- name: UpdatePaymentResult :exec
UPDATE payments SET status = $2, reference = $3 WHERE id = $1
`

type UpdatePaymentResultParams struct {
	ID        string
	Status    string
	Reference string
}

func (q *Queries) UpdatePaymentResult(ctx context.Context, arg UpdatePaymentResultParams) error {
	_, err := q.db.Exec(ctx, updatePaymentResult, arg.ID, arg.Status, arg.Reference)
	return err
}
